### ISSUE TITLE
World can't be loaded if there is a space in the directory name

### ISSUE THREAD

**Issue by ApocalypsjeNL** [magicus/pmanvil-converter#2]
When trying to load a world from a directory with a space in it (for example 'E:\Minecraft PE\PocketMine\worlds\world') then it's trying to load the world from 'E:\Minecraft' with the world name 'PE\PocketMine\worlds\world'

**Comment by magicus** [comment]
Thank you for your bug report. I'll not be bothered to try to address this. It's either an issue with properly quoting the path from Windows, or an issue with the original anvil-converter from Mojang.

However, I've updated the instructions in the README with a suggested workaround.

**Comment by magicus** [comment]
Fixed by 
https://github.com/magicus/pmanvil-converter/commit/2d5f664b3d0a7953431c848d60107746ca646231
