### ISSUE TITLE
how use 

### ISSUE THREAD

**Issue by llronaldoll** [magicus/pmanvil-converter#3]
I did not understand how it works, can you explain?

**Comment by magicus** [comment]
I'm sorry, this is targeted for developers. The instructions are in the readme. If you do not understand them, you should probably not be using this tool.

**Comment by llronaldoll** [comment]
Good morning, can you help me by converting a world that I used with my children at pmmp?

**Comment by magicus** [comment]
I'm not really interested in providing free one-to-one support, but I'll consider this a bug on the documentation. 

So tell me, how much of the documentation have you followed? Where did you get stuck?
