### ISSUE TITLE
Cant get it to work, 

### ISSUE THREAD

**Issue by 2cool4yothegamer** [magicus/pmanvil-converter#4]
I cant get the program to convert my pmanvil file to a anvil file for me to edit inside mineways. 
java -jar C:\Users\Gabe\Downloads\pmanvil-converter.jar
^^^^^
is how you open the program, yes it worked and gave me the steps
I continued to follow the steps dragging the files into the command prompt to get this
java -jar pmanvil-converter.jar C:\Users\Gabe\AppData\Roaming\.minecraft\saves Spawn
The path is where my Minecraft worlds are located and the "Spawn"  is the pmanvil file that I want to convert. When I run this it give me a error saying "Unable to access jarfile pmanvil-converter.jar" So it makes me feel as if the program is broken, or am I doing something wrong?

**Comment by magicus** [comment]
This is not an issue with pmanvil-converter. 

I'm not interested in providing free one-to-one support. However, it seems like your second command line lost the path to pmanvil-converter.jar. Try `java -jar C:\Users\Gabe\Downloads\pmanvil-converter.jar C:\Users\Gabe\AppData\Roaming.minecraft\saves Spawn`.
