### ISSUE TITLE
"Errors"

### ISSUE THREAD

**Issue by chaosfreak93** [magicus/pmanvil-converter#5]
When I want to convert a world from pmanvil to anvil. I got this error in the console "Failed to fetch input stream". Then when I
 copy the world the server crash. [crash-2020-09-04_18.20.43-server.txt](https://github.com/magicus/pmanvil-converter/files/5176708/crash-2020-09-04_18.20.43-server.txt). Can you look at it and tell me if it my fault or yours.

**Comment by magicus** [comment]
So this is a minecraft crash after starting with a converted world?

The error message says: "net.minecraft.server.v1_16_R2.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:PistonArm" 

I don't know where the "PistonArm" comes from, but apparently minecraft do not accept it. This is not a conversion. that pmanvil is handling. Perhaps you need some additional conversion.

**Comment by magicus** [comment]
@chaosfreak93 I did some googling for you :)

https://mcreator.net/wiki/minecraft-1144-resourcelocationexception-non-z0-9-character-path-location

Apparently an issue with your texture pack.

**Comment by chaosfreak93** [comment]
I use the default Minecraft Texture Pack. On Server and client. Server Java: PaperMC, Server Bedrock: PocketMine-MP. @magicus
