### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by chaosfreak93** [magicus/pmanvil-converter#6]
When I want to convert a world from pmanvil to anvil. I got this error in the console "Failed to fetch input stream". Then when I
copy the world the server crash. 
[crash-2020-09-04_18.20.43-server.txt](https://github.com/magicus/pmanvil-converter/files/5178092/crash-2020-09-04_18.20.43-server.txt)
. Can you look at it and tell me if it my fault or yours.

Is use on PocketMine and NukkitX the Vanilla Texture Pack

**Comment by magicus** [comment]
I'm sorry, I cannot help you.
